#!/usr/bin/python

import os
import sys
import subprocess
from yt_dlp import YoutubeDL

def download_video(url):
    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': '%(title)s.%(ext)s',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
        'quiet': True,
        'restrictfilenames': True,
    }

    with YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=True)
        print(info.get('title', None))
        return (info.get('title', None)).replace('-', '\\ ')

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python script.py <youtube_url>")
        sys.exit(1)

    youtube_url = sys.argv[1]
    title = download_video(youtube_url)
